# Generated by Django 4.1.5 on 2023-01-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use')], max_length=255),
        ),
    ]
