# Generated by Django 4.1.5 on 2023-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_store_manager',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
