# Generated by Django 4.1.5 on 2023-01-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_is_customer_remove_user_is_store_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
